/*
 * The demo-tank hass shim.
 *
 * The marketing site mounts the REAL OpenReef panel (openreef-panel.js, copied
 * verbatim from the integration) and hands it this object instead of Home
 * Assistant's. Recorded fixtures answer the read commands (generated by
 * site/tools/demo-fixtures.py running the actual backend handlers), a small
 * deterministic ocean model keeps the sensors breathing, and the interactive
 * writes (toggle, save, manual tests, settings) mutate an in-memory config so
 * the session feels alive. Nothing persists; a reload is a fresh tank.
 *
 * Honesty rule carried over from the site: the shim never fakes success for
 * actions that need real hardware — those throw a friendly "this needs a real
 * tank" error, which the panel surfaces in its own error slot.
 */

interface Fixtures {
  generatedAt: string;
  source: string;
  ws: Record<string, any>;
  states: Record<string, any>;
}

export interface DemoHass {
  states: Record<string, any>;
  callWS(msg: Record<string, any>): Promise<any>;
  callApi(method: string, path: string): Promise<any>;
  connection: {
    subscribeMessage(cb: (msg: any) => void, sub: any): Promise<() => void>;
    subscribeEvents(cb: (ev: any) => void, type?: string): Promise<() => void>;
    sendMessagePromise(msg: any): Promise<any>;
  };
  user: { name: string; is_admin: boolean };
}

const clone = <T,>(v: T): T => structuredClone(v);

const ISO_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/;

/** Shift every ISO timestamp by (now − generatedAt) so relative story beats
 * ("water change yesterday", "ICP twelve days ago") never go stale. */
function rebase<T>(node: T, deltaMs: number): T {
  if (Array.isArray(node)) return node.map((n) => rebase(n, deltaMs)) as unknown as T;
  if (node && typeof node === "object") {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(node as Record<string, unknown>)) out[k] = rebase(v, deltaMs);
    return out as unknown as T;
  }
  if (typeof node === "string" && ISO_RE.test(node)) {
    return new Date(Date.parse(node) + deltaMs).toISOString() as unknown as T;
  }
  return node;
}

/* ------------------------------------------------------------------------- *
 * The ocean model: value(entity, t) is a pure function of wall-clock time,
 * so the live tick and every trend window (1 h or 30 d) tell one consistent
 * story — diel pH swing, afternoon temperature peak, slow salinity drift.
 * ------------------------------------------------------------------------- */

const HOUR = 3_600_000;
const DAY = 24 * HOUR;

type Curve = { base: number; dp: number; parts: Array<[amp: number, periodMs: number, phase: number]> };

/** Curves are derived from whatever numeric sensors the fixture set carries
 * (seeded showroom OR a recording of a real tank), keyed by unit/name so the
 * diel shapes stay biologically plausible: afternoon temp peak, daytime pH
 * high, slow salinity drift. Baseline = the fixture's own current value. */
function curveFor(entityId: string, st: any): Curve | null {
  const base = Number.parseFloat(st?.state);
  if (!Number.isFinite(base)) return null;
  const unit = String(st?.attributes?.unit_of_measurement ?? "").toLowerCase();
  const id = entityId.toLowerCase();
  const dp = (String(st?.state).split(".")[1] ?? "").length;
  if (unit.includes("°") || st?.attributes?.device_class === "temperature") {
    return { base, dp, parts: [[0.22, DAY, -0.6], [0.05, 3.7 * HOUR, 1.3], [0.02, 0.7 * HOUR, 0.2]] };
  }
  if (id.includes("ph") && base > 6 && base < 9.5) {
    return { base, dp: Math.max(dp, 2), parts: [[0.09, DAY, -0.9], [0.012, 2.1 * HOUR, 0.8]] };
  }
  if (unit === "ppt" || id.includes("salin")) {
    return { base, dp, parts: [[0.06, 7 * DAY, 0.4], [0.02, 5.3 * HOUR, 2.6]] };
  }
  if (unit === "mv" || id.includes("orp")) {
    return { base, dp, parts: [[6, DAY, 2.0], [2.5, 1.7 * HOUR, 0.3]] };
  }
  // Generic gentle wobble: ±0.5 % of the baseline over the day.
  const amp = Math.abs(base) * 0.005 || 0.05;
  return { base, dp, parts: [[amp, DAY, 0.9], [amp * 0.4, 2.3 * HOUR, 1.7]] };
}

function makeValueAt(states: Record<string, any>) {
  const curves: Record<string, Curve> = {};
  for (const [id, st] of Object.entries(states)) {
    if (!id.startsWith("sensor.")) continue;
    const curve = curveFor(id, st);
    if (curve) curves[id] = curve;
  }
  return {
    curves,
    valueAt(entityId: string, tMs: number): number | null {
      const curve = curves[entityId];
      if (!curve) return null;
      let v = curve.base;
      for (const [amp, period, phase] of curve.parts) {
        v += amp * Math.sin((2 * Math.PI * tMs) / period + phase);
      }
      return Number(v.toFixed(curve.dp));
    },
  };
}

/* ------------------------------------------------------------------------- */

const demoBlocked = (what: string): never => {
  throw new Error(
    `Demo tank: ${what} needs real hardware behind it. On your own reef this button does the thing — that's rather the point.`,
  );
};

// Journal-style writes (logging a dose, a jar sign, a salinity reading…)
// aren't a hardware limit — they're an honesty one: nothing here persists.
const demoNoPersist = (what: string): never => {
  throw new Error(
    `Demo tank: ${what} needs somewhere to live, and nothing here persists — a reload is a fresh tank. On your reef it goes in the log and stays.`,
  );
};

const PERSIST_ONLY =
  /^openreef\/(consumable_|cultures_|nps_hand_feed|nps_fridge_bottle|nps_cysts_opened|nps_hatch_clock|nps_reservoir_discard|nps_enrich_loaded|mixing_(log_salinity|mark_used|salt_stock|set_level|filters_changed|unit_replaced)|cooling_learning)/;

export async function createDemoHass(onMutate: () => void): Promise<{ hass: DemoHass; fixtures: Fixtures; stop: () => void }> {
  const raw: Fixtures = await (await fetch("/demo/fixtures.json")).json();
  const deltaMs = Date.now() - Date.parse(raw.generatedAt);
  const ws = rebase(raw.ws, deltaMs);
  const states: Record<string, any> = rebase(raw.states, deltaMs);

  // The live, session-local config. Reads clone it; interactive writes mutate it.
  const envelope = ws["openreef/get_config"];
  let config = clone(envelope.config);
  const { curves, valueAt } = makeValueAt(states);

  const nowIso = () => new Date().toISOString();

  const touchState = (entityId: string, state: string) => {
    const st = states[entityId];
    if (!st) return;
    st.state = state;
    st.last_changed = nowIso();
    st.last_updated = st.last_changed;
  };

  const configEnvelope = () => ({
    ...clone(envelope),
    config: clone(config),
    settings: clone(config),
  });

  const routes: Record<string, (msg: Record<string, any>) => any> = {
    "openreef/get_config": () => configEnvelope(),

    "openreef/validate_config": () => clone(envelope.validation),

    "openreef/save_config": (msg) => {
      if (msg.config && typeof msg.config === "object") config = clone(msg.config);
      return configEnvelope();
    },

    "openreef/toggle_equipment": (msg) => {
      const equipment = config?.equipment?.[msg.equipment_id];
      if (!equipment) throw new Error("Unknown equipment.");
      const label = equipment.label || msg.equipment_id;
      if (!equipment.armed) {
        throw new Error(
          `${label} is locked: it has never been armed. In OpenReef you map an outlet, then arm it yourself — until then the software cannot touch it. That rule holds even in the demo.`,
        );
      }
      const entityId = equipment.switch_entity_id;
      const current = states[entityId]?.state === "on";
      touchState(entityId, current ? "off" : "on");
      return { config: clone(config) };
    },

    "openreef/search_entities": (msg) => {
      const terms: string[] = [
        ...(msg.target?.keywords ?? []),
        ...(msg.target?.prefer ?? []),
      ].map((t: string) => t.toLowerCase());
      const domains: string[] = msg.target?.domains ?? [];
      const candidates = Object.entries(states)
        .filter(([id]) => domains.length === 0 || domains.includes(id.split(".")[0]))
        .map(([id, st]) => ({
          entity_id: id,
          name: st.attributes?.friendly_name || id,
          score: terms.reduce(
            (n, t) => n + (id.includes(t) || String(st.attributes?.friendly_name ?? "").toLowerCase().includes(t) ? 1 : 0),
            0,
          ),
        }))
        .sort((a, b) => b.score - a.score)
        .slice(0, msg.limit ?? 10)
        .map(({ entity_id, name }) => ({ entity_id, name }));
      return { candidates };
    },

    "openreef/generate_spawning_program": () => clone(ws["openreef/generate_spawning_program"]),
    "openreef/awc_summary": () => clone(ws["openreef/awc_summary"]),
    "openreef/dosing_summary": () => clone(ws["openreef/dosing_summary"]),
    "openreef/icp_dashboard": (msg) =>
      clone(ws["openreef/icp_dashboard"]),
    "openreef/lighting_window": () => clone(ws["openreef/lighting_window"]),
    "openreef/list_reef_presets": () => clone(ws["openreef/list_reef_presets"]),
    "openreef/guardian_status": () => clone(ws["openreef/guardian_status"]),
    "openreef/vision_summary": () => clone(ws["openreef/vision_summary"]),
    // The Helm-era pages (0.7.40+): the food shelf + hatchery, the culture
    // jars, the mixing station, cooling headroom, the spawning executor.
    "openreef/nps_summary": () => clone(ws["openreef/nps_summary"]),
    "openreef/cultures_summary": () => clone(ws["openreef/cultures_summary"]),
    "openreef/mixing_summary": () => clone(ws["openreef/mixing_summary"]),
    "openreef/cooling_status": () => clone(ws["openreef/cooling_status"]),
    "openreef/spawning_execution_status": () => clone(ws["openreef/spawning_execution_status"]),

    // Quiet, safe empties — tabs that list media simply have none in the demo.
    "openreef/list_timelapse_frames": () => ({ frames: [] }),
    "openreef/list_feed_sessions": () => ({ sessions: [] }),
    "openreef/list_feed_frames": () => ({ frames: [] }),

    // Friendly refusals for hardware actions, named so the message reads well.
    "openreef/awc_run_now": () => demoBlocked("running a water change"),
    "openreef/awc_calibrate": () => demoBlocked("pump calibration"),
    "openreef/awc_calibration_run": () => demoBlocked("pump calibration"),
    "openreef/capture_now": () => demoBlocked("camera capture"),
    "openreef/capture_timelapse_frame": () => demoBlocked("camera capture"),
    "openreef/test_notification": () => demoBlocked("sending a phone notification"),
    "openreef/guardian_chat": () => demoBlocked("talking to the live avatar"),
    "openreef/guardian_voice": () => demoBlocked("talking to the live avatar"),
    "openreef/guardian_simli_session": () => demoBlocked("the live avatar"),
    "openreef/dosing_dose_now": () => demoBlocked("firing a dosing pump"),

    // Not a hardware limit — an honesty one: nothing in the demo persists, so
    // an uploaded photo would vanish on reload. The glyph picker works fine.
    "openreef/coral_photo_upload": () => {
      throw new Error(
        "Demo tank: photo uploads need somewhere to live, and nothing here persists — a reload is a fresh tank. On your reef the photo stays on the coral.",
      );
    },
    "openreef/dosing_prime": () => demoBlocked("priming a dosing pump"),
    "openreef/dosing_calibrate_start": () => demoBlocked("dosing calibration"),
  };

  // Drift telemetry for tools/demo-smoke.mjs: every openreef/* command the
  // panel sends that no route answers lands here. During a tabs-only sweep
  // this list must stay empty — anything in it is a read the panel now needs
  // and the fixtures don't carry (i.e. the demo has drifted behind the panel).
  const unrouted: string[] = ((window as any).__demoUnrouted = []);

  const hass: DemoHass = {
    states,
    callWS: async (msg) => {
      const route = routes[msg.type];
      if (route) return route(msg);
      if (String(msg.type).startsWith("openreef/")) {
        const type = String(msg.type);
        unrouted.push(type);
        const label = `"${type.replace("openreef/", "").replace(/_/g, " ")}"`;
        return PERSIST_ONLY.test(type) ? demoNoPersist(label) : demoBlocked(label);
      }
      return {};
    },
    callApi: async (_method, path) => {
      // The only REST the panel uses: /api/history/period/<start>?...&filter_entity_id=<id>
      const m = /^history\/period\/([^?]+)\?(.*)$/.exec(path);
      if (!m) return [];
      const params = new URLSearchParams(m[2]);
      const entityId = params.get("filter_entity_id") ?? "";
      const start = Date.parse(decodeURIComponent(m[1]));
      const end = Date.parse(params.get("end_time") ?? "") || Date.now();
      if (!curves[entityId] || !Number.isFinite(start)) return [[]];
      const steps = 240;
      const stepMs = Math.max((end - start) / steps, 30_000);
      const points = [];
      for (let t = start; t <= end; t += stepMs) {
        points.push({
          entity_id: entityId,
          state: String(valueAt(entityId, t)),
          last_changed: new Date(t).toISOString(),
        });
      }
      return [points];
    },
    connection: {
      subscribeMessage: async () => () => {},
      subscribeEvents: async () => () => {},
      sendMessagePromise: async (msg) => hass.callWS(msg),
    },
    user: { name: "Demo visitor", is_admin: true },
  };

  // The tide: every 5 s the modelled sensors move a little and the panel is
  // nudged the way HA nudges it (a fresh hass assignment). The panel's own
  // guards decide whether it's safe to re-render.
  const tick = window.setInterval(() => {
    const t = Date.now();
    for (const entityId of Object.keys(curves)) {
      const v = valueAt(entityId, t);
      if (v !== null && states[entityId]) touchState(entityId, String(v));
    }
    onMutate();
  }, 5000);

  return { hass, fixtures: raw, stop: () => window.clearInterval(tick) };
}
