import { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import Opener from "../demo/Opener";
import { createDemoHass } from "../demo/shim";
import { GITHUB_URL } from "../copy";
import "../styles.css";
import "./demo.css";

/*
 * /demo/ — the Showroom Reef.
 *
 * This page mounts the REAL OpenReef panel (the same openreef-panel.js that
 * ships in the HACS integration, copied verbatim by site/tools/demo-fixtures.py)
 * against a browser-side hass shim fed with fixtures generated by the actual
 * backend handlers. It is not a mock-up of the product; it is the product,
 * with the ocean simulated underneath it.
 */

function DemoPage() {
  const hostRef = useRef<HTMLDivElement>(null);
  const panelRef = useRef<any>(null);
  const [status, setStatus] = useState<"loading" | "ready" | "failed">("loading");
  const [opener, setOpener] = useState<boolean>(() => !localStorage.getItem("openreef:demo:opener"));

  useEffect(() => {
    // The panel's guided tour is replaced by the scripted opener.
    localStorage.setItem("openreef:onboarding:v1:done", "1");
    let cancelled = false;
    let stopTick = () => {};
    (async () => {
      try {
        await Promise.race([
          customElements.whenDefined("openreef-panel"),
          new Promise((_, reject) => setTimeout(() => reject(new Error("panel script missing")), 8000)),
        ]);
        const { hass, stop } = await createDemoHass(() => {
          if (panelRef.current) panelRef.current.hass = hass;
        });
        stopTick = stop;
        if (cancelled) {
          stop();
          return;
        }
        const el = document.createElement("openreef-panel");
        panelRef.current = el;
        hostRef.current!.appendChild(el);
        (el as any).hass = hass;
        setStatus("ready");
      } catch (err) {
        console.error("demo failed to start", err);
        if (!cancelled) setStatus("failed");
      }
    })();
    return () => {
      cancelled = true;
      stopTick();
    };
  }, []);

  return (
    <>
      <header className="demo-banner">
        <div className="demo-banner-title">
          <a className="demo-banner-brand" href="/">
            <img src="/logo.png" alt="" /> OpenReef
          </a>
          <span className="demo-banner-label">
            <strong>The Showroom Reef</strong> — the real panel, on a simulated tank. Seeded data,
            live tide. Nothing you press here can harm an animal.
          </span>
        </div>
        <nav className="demo-banner-actions">
          <button className="btn btn-ghost btn-small" onClick={() => setOpener(true)}>
            Replay the 2 AM save
          </button>
          <a className="btn btn-ghost btn-small" href={GITHUB_URL}>
            Source
          </a>
          <a className="btn btn-primary btn-small" href="/#cta">
            Join the beta
          </a>
        </nav>
      </header>

      <main className="demo-main">
        {status === "loading" && <p className="demo-status">Filling the tank…</p>}
        {status === "failed" && (
          <div className="demo-status">
            <p>The demo tank didn't fill — that's on us, not your browser.</p>
            <p>
              <a href="/">Back to the dive</a> · <a href="/#features">See the screenshots instead</a>
            </p>
          </div>
        )}
        <div ref={hostRef} className="demo-host" data-ready={status === "ready"} />
      </main>

      {opener && status === "ready" && <Opener onDone={() => setOpener(false)} />}
    </>
  );
}

createRoot(document.getElementById("root")!).render(<DemoPage />);
